directml版をダウンロードする処理を追加
VOICEVOX/onnxruntime-rs pull request #1
Opened 2022-07-29 14:29 UTC by qwerty2501

directml版をダウンロードする処理を追加しました

--features directmlを追加するようにするとdirectml版をダウンロードするようになります

refs https://github.com/VOICEVOX/voicevox_core/pull/205#issuecomment-1199112315

2022-07-29 14:41 UTC, qwerty2501 commented
バグがありそうなのでdraft

2022-07-29 14:46 UTC, qwerty2501 commented
修正した

2022-07-29 16:00 UTC, Hiroshiba approved these changes
LGTM！！！

2022-07-31 07:39 UTC, PickledChair requested changes
DirectML 対応ありがとうございます！　レスポンスが遅くなりすみません。
ほぼ問題なさそうでしたが、修正が必要な個所があったのでコメントしました。

また、`directml` feature を voicevox_core から使えるようにするために、onnxruntime crate の Cargo.toml の `[features]` に `directml = ["onnxruntime-sys/directml"]` を加える必要があると思いました！

2022-07-31 07:39 UTC, PickledChair commented on onnxruntime-sys/build.rs
> +                TRIPLET.arch.as_onnx_str()
実際に voicevox_core で使ってみてリンクエラーになり気づいたのですが、`TRIPLET.arch.as_onnx_str()` だと DirectML 版 onnxruntime のディレクトリの命名規則と合わないようです（例えば `win-x64` という名前になってほしいところが `win-x86-64` という名前になってしまう）。以下のように記述したところビルドが通りました。

```suggestion
                match TRIPLET.arch {
                    Architecture::X86 => Cow::from("x86"),
                    Architecture::X86_64 => Cow::from("x64"),
                    Architecture::Arm => Cow::from("arm"),
                    Architecture::Arm64 => Cow::from("arm64"),
                }
```

2022-07-31 08:15 UTC, qwerty2501 commented on onnxruntime-sys/build.rs
> +                TRIPLET.arch.as_onnx_str()
ここx64に書き換えてしまうと今度はほかのダウンロードがうまく行かなくなってしまうのでちょっとかんがえるひつようがありそうですね

2022-07-31 08:20 UTC, PickledChair commented on onnxruntime-sys/build.rs
> +                TRIPLET.arch.as_onnx_str()
> ここx64に書き換えてしまうと今度はほかのダウンロードがうまく行かなくなってしまうのでちょっとかんがえるひつようがありそうですね

DirectMLの場合だけ書き換えをすることを例示したつもりだったのですが、他のダウンロードに対してどのような影響がありそうでしょうか？（すみません、私が理解できていないだけかもしれません）

2022-07-31 08:24 UTC, qwerty2501 commented on onnxruntime-sys/build.rs
> +                TRIPLET.arch.as_onnx_str()
@PickledChair 新しく専用の関数を定義する形で修正しました

2022-07-31 08:25 UTC, qwerty2501 commented
> また、directml feature を voicevox_core から使えるようにするために、onnxruntime crate の Cargo.toml の [features] に directml = ["onnxruntime-sys/directml"] を加える必要があると思いました！

そうでした。忘れてました。
追加しておきました

2022-07-31 08:31 UTC, PickledChair commented on onnxruntime-sys/build.rs
> +                TRIPLET.arch.as_onnx_str()
@qwerty2501 なるほど、dll以外のダウンロード内容物に関して操作が必要になったときには関数化されていた方が便利ですね。より良い形だと思いました！

2022-07-31 08:36 UTC, PickledChair requested changes
すみません、もう一箇所確認をよろしくお願いします！

2022-07-31 08:36 UTC, PickledChair commented on onnxruntime-sys/build.rs
> +            Architecture::Arm64 => Cow::from("aarch64"),
すみません、細かいのですが arm64 の場合もディレクトリ名が `win-arm64` なので変更が必要です。

```suggestion
            Architecture::Arm64 => Cow::from("arm64"),
```

2022-07-31 08:39 UTC, qwerty2501 commented on onnxruntime-sys/build.rs
> +            Architecture::Arm64 => Cow::from("aarch64"),
修正しました

2022-07-31 08:45 UTC, PickledChair approved these changes
LGTM！！

2022-07-31 13:25 UTC, qwerty2501 commented
あー、これだとちょっとvoicevox_coreのrelease buildが作りづらいので、dllが非directmlを指定した時と同じディレクトリに展開されるように変えれないかやってみます

2022-07-31 14:02 UTC, qwerty2501 commented
通常時と同じディレクトリにコピーされるようにしてみました。念の為実行してみて問題ないか確認お願いします

2022-07-31 14:38 UTC, PickledChair commented
@qwerty2501 手元でビルドしてみましたが、問題ありませんでした！ CIの方で追加する処理が少なくなるので良さそうです……！

2022-08-01 16:41 UTC, Hiroshiba commented
マージします！

2022-08-01 16:41 UTC, merged